### ISSUE TITLE
USER STORY: creating polls to collect user feedback

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/my-first-agile-project#5]
As a **site administrator** I can **create a poll** so that I can receive **user feedback**

## Acceptance Criteria:

* Acceptance Criteria 1: The poll's title should be changeable 
* Acceptance Criteria 2: The poll's place should be reserved on the home page, with a placeholder message if there is no current poll 
* Acceptance Criteria 3: The poll should expire in 3 days after it was created

## Tasks
- [ ] Task 1:  Create the design for the poll with HTML and CSS
- [ ] Task 2: Create a JavaScript function to validate that the expiry date is at least after 3 days.
- [ ] Task 3: Make the expired polls disappear from the page
- [ ] Task 4: Test the functionality
